//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRazor.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebRazor.Resources.Pages.CreateModel", typeof(CreateModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs disposed of by the registrar, the case management officer or authorized personnel or by operation of the rules.
        /// </summary>
        public static string _1_1_4_Heading {
            get {
                return ResourceManager.GetString("1_1_4_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The civil appeals, cross-appeals, references, and JRs disposed of by the registrar take into account the certificates of lapse of appeal issued by the registry..
        /// </summary>
        public static string _1_1_4_Info {
            get {
                return ResourceManager.GetString("1_1_4_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of appeals, cross-appeals, references, bail reviews, and judicial reviews (JRs).
        /// </summary>
        public static string _1_Heading {
            get {
                return ResourceManager.GetString("1_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One notice of appeal counts as one appeal filed and one appeal disposed of, even though a number of related cases may be grouped together and heard at one hearing (example: if 10 cases are grouped together and heard together but are the subject of 10 notices of appeal, this counts as 10 appeals filed and 10 appeals disposed of). A notice of appeal containing both an appeal against conviction and against sentence, shall be counted as two appeals, but when heard together shall be counted as a single hearing.&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _1_Info {
            get {
                return ResourceManager.GetString("1_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A draft form was started for the selected Court and Reporting Year. 
        ///Please choose one of the following options:.
        /// </summary>
        public static string Alert_DraftFound_AskLoad {
            get {
                return ResourceManager.GetString("Alert_DraftFound_AskLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The draft save failed..
        /// </summary>
        public static string Alert_DraftSavedFailed {
            get {
                return ResourceManager.GetString("Alert_DraftSavedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success - The draft was saved successfully - Close.
        /// </summary>
        public static string Alert_DraftSavedSuccess {
            get {
                return ResourceManager.GetString("Alert_DraftSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record delete failed..
        /// </summary>
        public static string Alert_RecordDeleteFailed {
            get {
                return ResourceManager.GetString("Alert_RecordDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record retrieval failed..
        /// </summary>
        public static string Alert_RecordRetrievalFailed {
            get {
                return ResourceManager.GetString("Alert_RecordRetrievalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form has already been submitted for the selected Court and Year. For more information or changes, please contact the CJC department.
        ///.
        /// </summary>
        public static string AlertRecordAlreadyCompleted {
            get {
                return ResourceManager.GetString("AlertRecordAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Aria_Close {
            get {
                return ResourceManager.GetString("Aria_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Court and Reporting Year.
        /// </summary>
        public static string BasicInfo_SectionTitle {
            get {
                return ResourceManager.GetString("BasicInfo_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Tab.
        /// </summary>
        public static string btn_NextTab {
            get {
                return ResourceManager.GetString("btn_NextTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Tab.
        /// </summary>
        public static string Btn_PreviousTab {
            get {
                return ResourceManager.GetString("Btn_PreviousTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Stats.
        /// </summary>
        public static string btnReviewStats {
            get {
                return ResourceManager.GetString("btnReviewStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conviction/acquittal.
        /// </summary>
        public static string Common_ConvictionAcquittal {
            get {
                return ResourceManager.GetString("Common_ConvictionAcquittal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Common_Other {
            get {
                return ResourceManager.GetString("Common_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence.
        /// </summary>
        public static string Common_Sentence {
            get {
                return ResourceManager.GetString("Common_Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Draft.
        /// </summary>
        public static string Continue_Draft {
            get {
                return ResourceManager.GetString("Continue_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court is required.
        /// </summary>
        public static string CourtRequired {
            get {
                return ResourceManager.GetString("CourtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string dob {
            get {
                return ResourceManager.GetString("dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct following errors:.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name should be atleast two characters long.
        /// </summary>
        public static string FirstNameTwoChars {
            get {
                return ResourceManager.GetString("FirstNameTwoChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date is Required.
        /// </summary>
        public static string FromDateRequired {
            get {
                return ResourceManager.GetString("FromDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court Application (App).
        /// </summary>
        public static string hdgCreateheading1 {
            get {
                return ResourceManager.GetString("hdgCreateheading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entry Form.
        /// </summary>
        public static string hdgDataEntryForm {
            get {
                return ResourceManager.GetString("hdgDataEntryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sidebar tabs will appear once you fill the Name of Court and Reporting Year fields..
        /// </summary>
        public static string Info_SidebarAppearsAfterBasicInfo {
            get {
                return ResourceManager.GetString("Info_SidebarAppearsAfterBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name should be atleast two characters long.
        /// </summary>
        public static string LastNameTwoChars {
            get {
                return ResourceManager.GetString("LastNameTwoChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs filed but still pending as of December 31&lt;sup&gt;st&lt;/sup&gt; of the previous year.
        /// </summary>
        public static string Lbl_1_1_1 {
            get {
                return ResourceManager.GetString("Lbl_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs filed.
        /// </summary>
        public static string Lbl_1_1_2 {
            get {
                return ResourceManager.GetString("Lbl_1_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs disposed of by judgment.
        /// </summary>
        public static string Lbl_1_1_3 {
            get {
                return ResourceManager.GetString("Lbl_1_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs settled by judicial mediation.
        /// </summary>
        public static string Lbl_1_1_5 {
            get {
                return ResourceManager.GetString("Lbl_1_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs disposed of by other means.
        /// </summary>
        public static string Lbl_1_1_6 {
            get {
                return ResourceManager.GetString("Lbl_1_1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of civil appeals, cross-appeals, references, and JRs.
        /// </summary>
        public static string Lbl_1_1_7 {
            get {
                return ResourceManager.GetString("Lbl_1_1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil appeals, cross-appeals, references, and JRs filed, disposed of, and abandoned or withdrawn.
        /// </summary>
        public static string Lbl_1_1_Title {
            get {
                return ResourceManager.GetString("Lbl_1_1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals, cross-appeals, references and bail reviews filed but still pending as of December 31&lt;sup&gt;st&lt;/sup&gt; of the previous year.
        /// </summary>
        public static string Lbl_1_2_1 {
            get {
                return ResourceManager.GetString("Lbl_1_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals, cross-appeals, references and bail reviews filed.
        /// </summary>
        public static string Lbl_1_2_2 {
            get {
                return ResourceManager.GetString("Lbl_1_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals, cross-appeals, references and bail reviews disposed of by judgment.
        /// </summary>
        public static string Lbl_1_2_3 {
            get {
                return ResourceManager.GetString("Lbl_1_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals, cross-appeals, references and bail reviews disposed of by other means.
        /// </summary>
        public static string Lbl_1_2_4 {
            get {
                return ResourceManager.GetString("Lbl_1_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of criminal appeals, cross-appeals, references and bail reviews.
        /// </summary>
        public static string Lbl_1_2_5 {
            get {
                return ResourceManager.GetString("Lbl_1_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conviction appeal and sentence appeal are heard together.
        /// </summary>
        public static string Lbl_1_2_CheckboxText {
            get {
                return ResourceManager.GetString("Lbl_1_2_CheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal appeals, cross-appeals, references and bail reviews filed, disposed of, and abandoned or withdrawn..
        /// </summary>
        public static string Lbl_1_2_Title {
            get {
                return ResourceManager.GetString("Lbl_1_2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil case decisions given at hearing.
        /// </summary>
        public static string Lbl_2_1_1 {
            get {
                return ResourceManager.GetString("Lbl_2_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil case reserved decisions.
        /// </summary>
        public static string Lbl_2_1_2 {
            get {
                return ResourceManager.GetString("Lbl_2_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil case decisions.
        /// </summary>
        public static string Lbl_2_1_Title {
            get {
                return ResourceManager.GetString("Lbl_2_1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal case decisions given at hearing.
        /// </summary>
        public static string Lbl_2_2_1 {
            get {
                return ResourceManager.GetString("Lbl_2_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of convictions/acquittals given at hearing.
        /// </summary>
        public static string Lbl_2_2_1_1 {
            get {
                return ResourceManager.GetString("Lbl_2_2_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sentences given at hearing.
        /// </summary>
        public static string Lbl_2_2_1_2 {
            get {
                return ResourceManager.GetString("Lbl_2_2_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of other criminal appeals given at hearing.
        /// </summary>
        public static string Lbl_2_2_1_3 {
            get {
                return ResourceManager.GetString("Lbl_2_2_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal case decisions filed after reserving.
        /// </summary>
        public static string Lbl_2_2_2 {
            get {
                return ResourceManager.GetString("Lbl_2_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of convictions/acquittals filed after reserving.
        /// </summary>
        public static string Lbl_2_2_2_1 {
            get {
                return ResourceManager.GetString("Lbl_2_2_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sentences filed after reserving.
        /// </summary>
        public static string Lbl_2_2_2_2 {
            get {
                return ResourceManager.GetString("Lbl_2_2_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of other criminal appeals filed after reserving.
        /// </summary>
        public static string Lbl_2_2_2_3 {
            get {
                return ResourceManager.GetString("Lbl_2_2_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal case decisions.
        /// </summary>
        public static string Lbl_2_2_Title {
            get {
                return ResourceManager.GetString("Lbl_2_2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil and criminal case decisions.
        /// </summary>
        public static string Lbl_2_Heading {
            get {
                return ResourceManager.GetString("Lbl_2_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Bench decisions/judgments.
        /// </summary>
        public static string Lbl_3_1 {
            get {
                return ResourceManager.GetString("Lbl_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reserved decisions/judgments.
        /// </summary>
        public static string Lbl_3_2 {
            get {
                return ResourceManager.GetString("Lbl_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of Bench and reserved decisions/judgments.
        /// </summary>
        public static string Lbl_3_Heading {
            get {
                return ResourceManager.GetString("Lbl_3_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This time interval refers to the interval from the time a notice of appeal is filed (either as of right or after a motion for leave to appeal has been granted) to the time the appellant’s factum is filed and the appeal is ready to be set down for a hearing. The appeal is considered ready to be set down for a hearing on the date at which the appellant has done everything required by the rules of court to prepare an appeal for hearing (typically the serving and filing of the appeal book, transcripts and appel [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Lbl_4_1 {
            get {
                return ResourceManager.GetString("Lbl_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals where the interval from the notice of appeal to filing of the appellant’s factum took less than 6 months.
        /// </summary>
        public static string Lbl_4_1_1 {
            get {
                return ResourceManager.GetString("Lbl_4_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals where the interval from the notice of appeal to filing of the appellant’s factum took between 6 to 12 months.
        /// </summary>
        public static string Lbl_4_1_2 {
            get {
                return ResourceManager.GetString("Lbl_4_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals where the interval from the notice of appeal to filing of the appellant’s factum took more than 12 months.
        /// </summary>
        public static string Lbl_4_1_3 {
            get {
                return ResourceManager.GetString("Lbl_4_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals where the interval from the notice of appeal to filing of the appellant’s factum took less than 6 months for:.
        /// </summary>
        public static string Lbl_4_1_4 {
            get {
                return ResourceManager.GetString("Lbl_4_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conviction/acquittal.
        /// </summary>
        public static string Lbl_4_1_4_1 {
            get {
                return ResourceManager.GetString("Lbl_4_1_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal cases.
        /// </summary>
        public static string Lbl_4_1_CriminalCases {
            get {
                return ResourceManager.GetString("Lbl_4_1_CriminalCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil and criminal case time intervals.
        /// </summary>
        public static string Lbl_4_Heading {
            get {
                return ResourceManager.GetString("Lbl_4_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil cases.
        /// </summary>
        public static string Lbl_CivilCases {
            get {
                return ResourceManager.GetString("Lbl_CivilCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal cases.
        /// </summary>
        public static string Lbl_CriminalCases {
            get {
                return ResourceManager.GetString("Lbl_CriminalCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Lbl_From {
            get {
                return ResourceManager.GetString("Lbl_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Court.
        /// </summary>
        public static string Lbl_NameOfCourt {
            get {
                return ResourceManager.GetString("Lbl_NameOfCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting Year.
        /// </summary>
        public static string Lbl_ReportingYear {
            get {
                return ResourceManager.GetString("Lbl_ReportingYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Lbl_To {
            get {
                return ResourceManager.GetString("Lbl_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft Form.
        /// </summary>
        public static string Modal_DraftFound_Title {
            get {
                return ResourceManager.GetString("Modal_DraftFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the following sections:.
        /// </summary>
        public static string Modal_Validation_Title {
            get {
                return ResourceManager.GetString("Modal_Validation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs filed but still pending as of December 31&lt;sup&gt;st&lt;/sup&gt; of the previous year.
        /// </summary>
        public static string Msg_1_1_1 {
            get {
                return ResourceManager.GetString("Msg_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs filed.
        /// </summary>
        public static string Msg_1_1_2 {
            get {
                return ResourceManager.GetString("Msg_1_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs disposed of by judgment.
        /// </summary>
        public static string Msg_1_1_3 {
            get {
                return ResourceManager.GetString("Msg_1_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs disposed of by the registrar, the case management officer or authorized personnel or by operation of the rules.
        /// </summary>
        public static string Msg_1_1_4 {
            get {
                return ResourceManager.GetString("Msg_1_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs settled by judicial mediation.
        /// </summary>
        public static string Msg_1_1_5 {
            get {
                return ResourceManager.GetString("Msg_1_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs disposed of by other means.
        /// </summary>
        public static string Msg_1_1_6 {
            get {
                return ResourceManager.GetString("Msg_1_1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of civil appeals, cross-appeals, references, and JRs.
        /// </summary>
        public static string Msg_1_1_7 {
            get {
                return ResourceManager.GetString("Msg_1_1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs filed of criminal appeals, cross-appeals, references and bail reviews filed but still pending as of December 31&lt;sup&gt;st&lt;/sup&gt; of the previous year.
        /// </summary>
        public static string Msg_1_2_1 {
            get {
                return ResourceManager.GetString("Msg_1_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs filed of criminal appeals, cross-appeals, references and bail reviews filed.
        /// </summary>
        public static string Msg_1_2_2 {
            get {
                return ResourceManager.GetString("Msg_1_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals, cross-appeals, references and bail reviews disposed of by judgment.
        /// </summary>
        public static string Msg_1_2_3 {
            get {
                return ResourceManager.GetString("Msg_1_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals, cross-appeals, references and bail reviews disposed of by other means.
        /// </summary>
        public static string Msg_1_2_4 {
            get {
                return ResourceManager.GetString("Msg_1_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of criminal appeals, cross-appeals, references and bail reviews.
        /// </summary>
        public static string Msg_1_2_5 {
            get {
                return ResourceManager.GetString("Msg_1_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals, cross-appeals, references, and JRs filed of civil case decisions given at hearing.
        /// </summary>
        public static string Msg_2_1_1 {
            get {
                return ResourceManager.GetString("Msg_2_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil case reserved decisions.
        /// </summary>
        public static string Msg_2_1_2 {
            get {
                return ResourceManager.GetString("Msg_2_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal case decisions given at hearing.
        /// </summary>
        public static string Msg_2_2_1 {
            get {
                return ResourceManager.GetString("Msg_2_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of convictions/acquittals given at hearing.
        /// </summary>
        public static string Msg_2_2_1_1 {
            get {
                return ResourceManager.GetString("Msg_2_2_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sentences given at hearing.
        /// </summary>
        public static string Msg_2_2_1_2 {
            get {
                return ResourceManager.GetString("Msg_2_2_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of other criminal appeals given at hearing.
        /// </summary>
        public static string Msg_2_2_1_3 {
            get {
                return ResourceManager.GetString("Msg_2_2_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal case decisions filed after reserving.
        /// </summary>
        public static string Msg_2_2_2 {
            get {
                return ResourceManager.GetString("Msg_2_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of convictions/acquittals filed after reserving.
        /// </summary>
        public static string Msg_2_2_2_1 {
            get {
                return ResourceManager.GetString("Msg_2_2_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sentences filed after reserving.
        /// </summary>
        public static string Msg_2_2_2_2 {
            get {
                return ResourceManager.GetString("Msg_2_2_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of other criminal appeals filed after reserving.
        /// </summary>
        public static string Msg_2_2_2_3 {
            get {
                return ResourceManager.GetString("Msg_2_2_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Bench decisions/judgments.
        /// </summary>
        public static string Msg_3_1 {
            get {
                return ResourceManager.GetString("Msg_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reserved decisions/judgments.
        /// </summary>
        public static string Msg_3_2 {
            get {
                return ResourceManager.GetString("Msg_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals where the interval from the notice of appeal to filing of the appellant’s factum took less than 6 months.
        /// </summary>
        public static string Msg_4_1_1 {
            get {
                return ResourceManager.GetString("Msg_4_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals where the interval from the notice of appeal to filing of the appellant’s factum took between 6 to 12 months.
        /// </summary>
        public static string Msg_4_1_2 {
            get {
                return ResourceManager.GetString("Msg_4_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals where the interval from the notice of appeal to filing of the appellant’s factum took more than 12 months.
        /// </summary>
        public static string Msg_4_1_3 {
            get {
                return ResourceManager.GetString("Msg_4_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conviction/acquittal.
        /// </summary>
        public static string Msg_4_1_4_1 {
            get {
                return ResourceManager.GetString("Msg_4_1_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the dates that correspond to the Reporting Year..
        /// </summary>
        public static string Msg_FromDate {
            get {
                return ResourceManager.GetString("Msg_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the name of your court..
        /// </summary>
        public static string Msg_NameOfCourt {
            get {
                return ResourceManager.GetString("Msg_NameOfCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your reporting year..
        /// </summary>
        public static string Msg_ReportingYear {
            get {
                return ResourceManager.GetString("Msg_ReportingYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the dates that correspond to the Reporting Year..
        /// </summary>
        public static string Msg_ToDate {
            get {
                return ResourceManager.GetString("Msg_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting Year is required.
        /// </summary>
        public static string ReportingYearRequired {
            get {
                return ResourceManager.GetString("ReportingYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of appeals, cross-appeals, references, bail reviews and JRs that have not been finalized as of December 31&lt;sup&gt;st&lt;/sup&gt;.
        /// </summary>
        public static string Sec10_101_Label {
            get {
                return ResourceManager.GetString("Sec10_101_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of appeals, cross-appeals, references, bail reviews and JRs that have not been finalized as of December 31st.
        /// </summary>
        public static string Sec10_101_Label_Plain {
            get {
                return ResourceManager.GetString("Sec10_101_Label_Plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of appeals, cross-appeals, references, bail reviews and JRs pending on December 31&lt;sup&gt;st&lt;/sup&gt;.
        /// </summary>
        public static string Sec10_Heading {
            get {
                return ResourceManager.GetString("Sec10_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation text for pending inventory measured as of December 31&lt;sup&gt;st&lt;/sup&gt;, including heard and unheard matters..
        /// </summary>
        public static string Sec10_Heading_Tooltip {
            get {
                return ResourceManager.GetString("Sec10_Heading_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular judges.
        /// </summary>
        public static string Sec11_111_DataMsg {
            get {
                return ResourceManager.GetString("Sec11_111_DataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular judges.
        /// </summary>
        public static string Sec11_111_Label {
            get {
                return ResourceManager.GetString("Sec11_111_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of judges of the court as of December 31st that have not elected a supernumerary status and have regular judicial duties..
        /// </summary>
        public static string Sec11_111_Tooltip {
            get {
                return ResourceManager.GetString("Sec11_111_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supernumerary judges.
        /// </summary>
        public static string Sec11_112_DataMsg {
            get {
                return ResourceManager.GetString("Sec11_112_DataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supernumerary judges.
        /// </summary>
        public static string Sec11_112_Label {
            get {
                return ResourceManager.GetString("Sec11_112_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of judges of the court as of December 31&lt;sup&gt;st&lt;/sup&gt; that hold office as supernumerary judges as per section 28 of the &lt;i&gt;Judges Act&lt;/i&gt;..
        /// </summary>
        public static string Sec11_112_Tooltip {
            get {
                return ResourceManager.GetString("Sec11_112_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of judges (as of December 31&lt;sup&gt;st&lt;/sup&gt;).
        /// </summary>
        public static string Sec11_Heading {
            get {
                return ResourceManager.GetString("Sec11_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comments.
        /// </summary>
        public static string Sec12_Heading {
            get {
                return ResourceManager.GetString("Sec12_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments should only be used on an exceptional basis. A true anomaly is a situation that considerably deviates from what is considered normal or expected..
        /// </summary>
        public static string Sec12_Heading_Tooltip {
            get {
                return ResourceManager.GetString("Sec12_Heading_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice of appeal to filing of the appellant’s factum.
        /// </summary>
        public static string Sec4_41_Heading {
            get {
                return ResourceManager.GetString("Sec4_41_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This time interval refers to the interval from the time a notice of appeal is filed (either as of right or after a motion for leave to appeal has been granted) to the time the appellant’s factum is filed and the appeal is ready to be set down for a hearing. The appeal is considered ready to be set down for a hearing on the date at which the appellant has done everything required by the rules of court to prepare an appeal for hearing (typically the serving and filing of the appeal book, transcripts and appel [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sec4_41_Tip {
            get {
                return ResourceManager.GetString("Sec4_41_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Number of civil appeals where the interval from the notice of appeal to filing of the appellant’s factum took less than 6 months).
        /// </summary>
        public static string Sec4_411_Label {
            get {
                return ResourceManager.GetString("Sec4_411_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Number of civil appeals where the interval from the notice of appeal to filing of the appellant’s factum took between 6 to 12 months).
        /// </summary>
        public static string Sec4_412_Label {
            get {
                return ResourceManager.GetString("Sec4_412_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Number of civil appeals where the interval from the notice of appeal to filing of the appellant’s factum took more than 12 months).
        /// </summary>
        public static string Sec4_413_Label {
            get {
                return ResourceManager.GetString("Sec4_413_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Number of criminal appeals where the interval from the notice of appeal to filing of the appellant’s factum took less than 6 months for:).
        /// </summary>
        public static string Sec4_414_Label {
            get {
                return ResourceManager.GetString("Sec4_414_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Number of criminal appeals where the interval from the notice of appeal to filing of the appellant’s factum took between 6 to 12 months for:).
        /// </summary>
        public static string Sec4_415_Label {
            get {
                return ResourceManager.GetString("Sec4_415_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals where the interval from the notice of appeal to filing of the appellant’s factum took more than 12 months for:.
        /// </summary>
        public static string Sec4_416_Label {
            get {
                return ResourceManager.GetString("Sec4_416_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filing of the appellant’s factum to hearing.
        /// </summary>
        public static string Sec4_42_Heading {
            get {
                return ResourceManager.GetString("Sec4_42_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This time interval refers to the time required from the time the appellant’s factum is filed to the time the case is heard. The time the appeal is heard is the actual day of the appeal hearing and &lt;u&gt;not&lt;/u&gt; the scheduled date of hearing.&lt;br /&gt;&lt;br /&gt;Where the hearing consumes more than one day, use the first day of hearing for calculating the filing of the appellant’s factum to hearing time interval and the hearing to final decision time interval..
        /// </summary>
        public static string Sec4_42_Tip {
            get {
                return ResourceManager.GetString("Sec4_42_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals where the time interval from filing of the appellant’s factum to the hearing took less than 6 months.
        /// </summary>
        public static string Sec4_421_Label {
            get {
                return ResourceManager.GetString("Sec4_421_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals where the time interval from filing of the appellant’s factum to the hearing took between 6 to 12 months.
        /// </summary>
        public static string Sec4_422_Label {
            get {
                return ResourceManager.GetString("Sec4_422_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals where the time interval from filing of the appellant’s factum to the hearing took more than 12 months.
        /// </summary>
        public static string Sec4_423_Label {
            get {
                return ResourceManager.GetString("Sec4_423_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals where the time interval from filing of the appellant’s factum to the hearing took less than 6 months for:.
        /// </summary>
        public static string Sec4_424_Label {
            get {
                return ResourceManager.GetString("Sec4_424_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals where the time interval from filing of the appellant’s factum to the hearing took between 6 to 12 months for:.
        /// </summary>
        public static string Sec4_425_Label {
            get {
                return ResourceManager.GetString("Sec4_425_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals where the time interval from filing of the appellant’s factum to the hearing took more than 12 months for:.
        /// </summary>
        public static string Sec4_426_Label {
            get {
                return ResourceManager.GetString("Sec4_426_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearing to final decision.
        /// </summary>
        public static string Sec4_43_Heading {
            get {
                return ResourceManager.GetString("Sec4_43_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This time interval refers to the time between the day of the hearing (actual day of hearing and &lt;u&gt;not&lt;/u&gt; the scheduled date of hearing) and the date of the decision/judgment..
        /// </summary>
        public static string Sec4_43_Tip {
            get {
                return ResourceManager.GetString("Sec4_43_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals where the time interval from the hearing to the final decision took less than 6 months.
        /// </summary>
        public static string Sec4_431_Label {
            get {
                return ResourceManager.GetString("Sec4_431_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals where the time interval from the hearing to the final decision took between 6 to 12 months.
        /// </summary>
        public static string Sec4_432_Label {
            get {
                return ResourceManager.GetString("Sec4_432_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of civil appeals where the time interval from the hearing to the final decision took more than 12 months.
        /// </summary>
        public static string Sec4_433_Label {
            get {
                return ResourceManager.GetString("Sec4_433_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals where the time interval from the hearing to the final decision took less than 6 months for:.
        /// </summary>
        public static string Sec4_434_Label {
            get {
                return ResourceManager.GetString("Sec4_434_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals where the time interval from the hearing to the final decision took between 6 to 12 months for:.
        /// </summary>
        public static string Sec4_435_Label {
            get {
                return ResourceManager.GetString("Sec4_435_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of criminal appeals where the time interval from the hearing to the final decision took more than 12 months for:.
        /// </summary>
        public static string Sec4_436_Label {
            get {
                return ResourceManager.GetString("Sec4_436_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil cases.
        /// </summary>
        public static string Sec4_CivilCases {
            get {
                return ResourceManager.GetString("Sec4_CivilCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Sec4_Comments_Label {
            get {
                return ResourceManager.GetString("Sec4_Comments_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal cases.
        /// </summary>
        public static string Sec4_CriminalCases {
            get {
                return ResourceManager.GetString("Sec4_CriminalCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For criminal cases, the time intervals and time periods should be reported for each of the following three categories of criminal appeals: 1) Conviction/acquittal, 2) Sentence, and 3) Other..
        /// </summary>
        public static string Sec4_CriminalCases_Tip {
            get {
                return ResourceManager.GetString("Sec4_CriminalCases_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Civil and criminal case time intervals).
        /// </summary>
        public static string Sec4_Heading {
            get {
                return ResourceManager.GetString("Sec4_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Civil and criminal case statistics are to be collected for three time intervals: 1) Notice of appeal to filing of the appellant’s factum (or the equivalent document), 2) Filing of appellant’s factum to hearing, and 3) Hearing to final decision.&lt;br /&gt;&lt;br /&gt;For each of these time intervals, information will be gathered for three time periods: 1) Less than 6 months, 2) Between 6 to 12 months, and 3) More than 12 months.).
        /// </summary>
        public static string Sec4_Heading_Tip {
            get {
                return ResourceManager.GetString("Sec4_Heading_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-person hearings.
        /// </summary>
        public static string Sec5_51_Label_Short {
            get {
                return ResourceManager.GetString("Sec5_51_Label_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of hearings held where all parties were present in court for the hearing. This description also includes situations where the counsel attended the hearing in-person but where the individual being represented attended remotely/virtually..
        /// </summary>
        public static string Sec5_51_Tip {
            get {
                return ResourceManager.GetString("Sec5_51_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual hearings.
        /// </summary>
        public static string Sec5_52_Label_Short {
            get {
                return ResourceManager.GetString("Sec5_52_Label_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of hearings held where all parties attended the hearing remotely/virtually..
        /// </summary>
        public static string Sec5_52_Tip {
            get {
                return ResourceManager.GetString("Sec5_52_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid hearings.
        /// </summary>
        public static string Sec5_53_Label_Short {
            get {
                return ResourceManager.GetString("Sec5_53_Label_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of hearings held where one or more parties were present in court for the hearing and one or more parties attended the hearing remotely/virtually..
        /// </summary>
        public static string Sec5_53_Tip {
            get {
                return ResourceManager.GetString("Sec5_53_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of hearings held in-person, virtually and in hybrid mode.
        /// </summary>
        public static string Sec5_54_Label {
            get {
                return ResourceManager.GetString("Sec5_54_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is auto-populated using fields 5.1 to 5.3.
        /// </summary>
        public static string Sec5_54_Tip {
            get {
                return ResourceManager.GetString("Sec5_54_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of in-person, virtual and hybrid hearings.
        /// </summary>
        public static string Sec5_Heading {
            get {
                return ResourceManager.GetString("Sec5_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of hearings in this section are to be collected for &lt;u&gt;hearings by a panel of judges only&lt;/u&gt;..
        /// </summary>
        public static string Sec5_Heading_Tip {
            get {
                return ResourceManager.GetString("Sec5_Heading_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motions and applications heard by a single judge.
        /// </summary>
        public static string Sec6_61_Label {
            get {
                return ResourceManager.GetString("Sec6_61_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of motions and applications filed before a single judge.
        /// </summary>
        public static string Sec6_611_Label {
            get {
                return ResourceManager.GetString("Sec6_611_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of motions and applications disposed of by order of a single judge.
        /// </summary>
        public static string Sec6_612_Label {
            get {
                return ResourceManager.GetString("Sec6_612_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of motions and applications before a single judge that were abandoned, withdrawn or dismissed administratively.
        /// </summary>
        public static string Sec6_613_Label {
            get {
                return ResourceManager.GetString("Sec6_613_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples of dismissed administratively include dismissed for want of prosecution, non-compliance with rules, applications where leave is denied, etc..
        /// </summary>
        public static string Sec6_613_Tip {
            get {
                return ResourceManager.GetString("Sec6_613_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motions and applications heard by a panel of three or more judges.
        /// </summary>
        public static string Sec6_62_Label {
            get {
                return ResourceManager.GetString("Sec6_62_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of motions and applications filed before a panel of three or more judges.
        /// </summary>
        public static string Sec6_621_Label {
            get {
                return ResourceManager.GetString("Sec6_621_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of motions and applications disposed of by order of a panel of three or more judges.
        /// </summary>
        public static string Sec6_622_Label {
            get {
                return ResourceManager.GetString("Sec6_622_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of panel motions and applications that were abandoned, withdrawn or dismissed administratively.
        /// </summary>
        public static string Sec6_623_Label {
            get {
                return ResourceManager.GetString("Sec6_623_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples of dismissed administratively include dismissed for want of prosecution, non-compliance with rules, applications where leave is denied, etc..
        /// </summary>
        public static string Sec6_623_Tip {
            get {
                return ResourceManager.GetString("Sec6_623_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motions and applications heard by a registrar.
        /// </summary>
        public static string Sec6_63_Label {
            get {
                return ResourceManager.GetString("Sec6_63_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of motions and applications filed before a registrar.
        /// </summary>
        public static string Sec6_631_Label {
            get {
                return ResourceManager.GetString("Sec6_631_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of motions and applications disposed of by order of a registrar.
        /// </summary>
        public static string Sec6_632_Label {
            get {
                return ResourceManager.GetString("Sec6_632_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of panel motions and applications that were abandoned, withdrawn or dismissed by a registrar or for administrative reasons.
        /// </summary>
        public static string Sec6_633_Label {
            get {
                return ResourceManager.GetString("Sec6_633_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples of administrative reasons include dismissed for want of prosecution, non-compliance with rules, applications where leave is denied, etc..
        /// </summary>
        public static string Sec6_633_Tip {
            get {
                return ResourceManager.GetString("Sec6_633_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of motions and applications.
        /// </summary>
        public static string Sec6_Heading {
            get {
                return ResourceManager.GetString("Sec6_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of motions and applications heard in chambers (single judge), in court (panels of three or more judges) and by registrars. In some jurisdictions, motions and applications can be heard by a master or other judicial officers.&lt;br /&gt;&lt;br /&gt;Motions and applications heard at the time of the hearing of an appeal are &lt;u&gt;not&lt;/u&gt; to be included. Motions and applications in writing should be included. Consent orders should also be included if judicial time is required to deal with them.&lt;br /&gt;&lt;br /&gt;With respe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sec6_Heading_Tip {
            get {
                return ResourceManager.GetString("Sec6_Heading_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of appeals involving an SRL at the hearing of the appeal on the merits.
        /// </summary>
        public static string Sec7_711_Label {
            get {
                return ResourceManager.GetString("Sec7_711_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of motions and applications involving an SRL at the hearing of a motion or an application (by a single judge, a panel or the registrar).
        /// </summary>
        public static string Sec7_712_Label {
            get {
                return ResourceManager.GetString("Sec7_712_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motions and applications heard at the time of the hearing of an appeal are &lt;u&gt;not&lt;/u&gt; to be included..
        /// </summary>
        public static string Sec7_712_Tip {
            get {
                return ResourceManager.GetString("Sec7_712_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of appeals, motions and applications involving an SRL at the hearing.
        /// </summary>
        public static string Sec7_713_Label {
            get {
                return ResourceManager.GetString("Sec7_713_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is auto-populated using fields 7.1.1 and 7.1.2..
        /// </summary>
        public static string Sec7_713_Tip {
            get {
                return ResourceManager.GetString("Sec7_713_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-Represented Litigants (SRLs).
        /// </summary>
        public static string Sec7_Heading {
            get {
                return ResourceManager.GetString("Sec7_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An SRL is a person who appears in court without representation from a lawyer. The litigant is not to be considered an SRL if the court has appointed counsel to assist the litigant.&lt;br /&gt;&lt;br /&gt;The number of appeals and the number of motions involving an SRL is &lt;u&gt;only&lt;/u&gt; collected at the hearing. For example, if a person is represented by a lawyer at the filing stage of an appeal or motion but is not represented at the hearing, the appeal or motion is considered an SRL case..
        /// </summary>
        public static string Sec7_Heading_Tip {
            get {
                return ResourceManager.GetString("Sec7_Heading_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 6 months.
        /// </summary>
        public static string Sec8_81_Label {
            get {
                return ResourceManager.GetString("Sec8_81_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between 6 to 12 months.
        /// </summary>
        public static string Sec8_82_Label {
            get {
                return ResourceManager.GetString("Sec8_82_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 12 months.
        /// </summary>
        public static string Sec8_83_Label {
            get {
                return ResourceManager.GetString("Sec8_83_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of decisions related to civil and criminal cases that are rendered based on the selected time period from the hearing date. The cases involving the &lt;i&gt;Youth Criminal Justice Act&lt;/i&gt; are not to be tracked separately. They should be counted as any other decision rendered..
        /// </summary>
        public static string Sec8_Decision_Tip {
            get {
                return ResourceManager.GetString("Sec8_Decision_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of decisions related to civil and criminal cases that are rendered in less than 6 months from the hearing date. The cases involving the &lt;i&gt;Youth Criminal Justice Act&lt;/i&gt; are not to be tracked separately. They should be counted as any other decision rendered..
        /// </summary>
        public static string Sec8_Decision1_Tip {
            get {
                return ResourceManager.GetString("Sec8_Decision1_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of decisions related to civil and criminal cases that are rendered between 6 to 12 months from the hearing date. The cases involving the &lt;i&gt;Youth Criminal Justice Act&lt;/i&gt; are not to be tracked separately. They should be counted as any other decision rendered..
        /// </summary>
        public static string Sec8_Decision2_Tip {
            get {
                return ResourceManager.GetString("Sec8_Decision2_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of decisions related to civil and criminal cases that are rendered in more than 12 months from the hearing date. The cases involving the &lt;i&gt;Youth Criminal Justice Act&lt;/i&gt; are not to be tracked separately. They should be counted as any other decision rendered..
        /// </summary>
        public static string Sec8_Decision3_Tip {
            get {
                return ResourceManager.GetString("Sec8_Decision3_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of decisions/judgments rendered.
        /// </summary>
        public static string Sec8_Heading {
            get {
                return ResourceManager.GetString("Sec8_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By a 3-member panel hearings.
        /// </summary>
        public static string Sec9_91_Label {
            get {
                return ResourceManager.GetString("Sec9_91_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By a 5-member panel hearings.
        /// </summary>
        public static string Sec9_92_Label {
            get {
                return ResourceManager.GetString("Sec9_92_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of appeals that are heard.
        /// </summary>
        public static string Sec9_Heading {
            get {
                return ResourceManager.GetString("Sec9_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Court and Reporting Year.
        /// </summary>
        public static string Sidebar_BasicInfo {
            get {
                return ResourceManager.GetString("Sidebar_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab 1 - Number of appeals, cross-appeals, references, bail reviews, and judicial reviews (JRs).
        /// </summary>
        public static string Sidebar_Tab1 {
            get {
                return ResourceManager.GetString("Sidebar_Tab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of appeals, cross-appeals, references, bail reviews and JRs pending on December 31st.
        /// </summary>
        public static string Sidebar_Tab10 {
            get {
                return ResourceManager.GetString("Sidebar_Tab10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of judges (as of December 31st).
        /// </summary>
        public static string Sidebar_Tab11 {
            get {
                return ResourceManager.GetString("Sidebar_Tab11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comments and review statistics.
        /// </summary>
        public static string Sidebar_Tab12 {
            get {
                return ResourceManager.GetString("Sidebar_Tab12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab 2 - Civil and criminal case decisions.
        /// </summary>
        public static string Sidebar_Tab2 {
            get {
                return ResourceManager.GetString("Sidebar_Tab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab 3 - Total number of Bench and reserved decisions/judgments.
        /// </summary>
        public static string Sidebar_Tab3 {
            get {
                return ResourceManager.GetString("Sidebar_Tab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab 4 - Civil and criminal case time intervals.
        /// </summary>
        public static string Sidebar_Tab4 {
            get {
                return ResourceManager.GetString("Sidebar_Tab4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab 5 - Number of in-person, virtual and hybrid hearings.
        /// </summary>
        public static string Sidebar_Tab5 {
            get {
                return ResourceManager.GetString("Sidebar_Tab5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of motions and applications.
        /// </summary>
        public static string Sidebar_Tab6 {
            get {
                return ResourceManager.GetString("Sidebar_Tab6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-Represented Litigants (SRLs).
        /// </summary>
        public static string Sidebar_Tab7 {
            get {
                return ResourceManager.GetString("Sidebar_Tab7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of decisions/judgments rendered.
        /// </summary>
        public static string Sidebar_Tab8 {
            get {
                return ResourceManager.GetString("Sidebar_Tab8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of appeals that are heard.
        /// </summary>
        public static string Sidebar_Tab9 {
            get {
                return ResourceManager.GetString("Sidebar_Tab9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Form.
        /// </summary>
        public static string Start_New_Form {
            get {
                return ResourceManager.GetString("Start_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be included in this category, the settlement must have taken place at the time of judicial mediation and can include settlement, abandonment or withdrawal of the appeal at that time..
        /// </summary>
        public static string Tip_1_1_5 {
            get {
                return ResourceManager.GetString("Tip_1_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These appeals, cross-appeals, references, and JRs are to include those that are abandoned, withdrawn, dismissed for want of prosecution, non-compliance with rules, dispositions by a single judge, etc. The civil appeals, cross-appeals, references, and JRs abandoned or withdrawn by the registrar take into account the certificates of lapse of appeal issued by the registry..
        /// </summary>
        public static string Tip_1_1_6 {
            get {
                return ResourceManager.GetString("Tip_1_1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous year civil appeals, cross-appeals, references and JRs filed but still pending as of December 31&lt;sup&gt;st&lt;/sup&gt; of the previous year (1.1.1) plus new civil appeals, cross-appeals, references, and JRs filed (1.1.2) minus total number of civil appeals, cross-appeals, references, and JRs disposed of, settled by mediation, abandoned or withdrawn (1.1.3 to 1.1.6) = net civil appeals, cross-appeals, references, and JRs for the year..
        /// </summary>
        public static string Tip_1_1_7 {
            get {
                return ResourceManager.GetString("Tip_1_1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The criminal appeals, cross-appeals, references and bail reviews filed involving the &lt;i&gt;Youth Criminal Justice Act&lt;/i&gt; are not to be separately tracked as such. They should be counted as any other criminal appeals, cross-appeals, references and bail reviews filed..
        /// </summary>
        public static string Tip_1_2_2 {
            get {
                return ResourceManager.GetString("Tip_1_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The criminal appeals, cross-appeals, references and bail reviews disposed of by judgment involving the &lt;i&gt;Youth Criminal Justice Act&lt;/i&gt; are not to be tracked separately. They should be counted as any other criminal appeals, cross appeals, references and bail reviews disposed of..
        /// </summary>
        public static string Tip_1_2_3 {
            get {
                return ResourceManager.GetString("Tip_1_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These appeals, cross-appeals, references and bail reviews are to include those that are settled by judicial facilitations, abandoned, withdrawn, dismissed for want of prosecution, non-compliance with rules, and disposed of by a single judge, etc..
        /// </summary>
        public static string Tip_1_2_4 {
            get {
                return ResourceManager.GetString("Tip_1_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal appeals, cross-appeals, references and bail reviews filed but still pending as of December 31st of the previous year (1.2.1) plus new criminal appeals, cross-appeals, references and bail reviews filed (1.2.2) minus total number of criminal appeals, cross-appeals, references and bail reviews disposed of, settled by judicial facilitations, abandoned or withdrawn (1.2.3 to 1.2.4) = net criminal appeals, cross-appeals, references and bail reviews for the year..
        /// </summary>
        public static string Tip_1_2_5 {
            get {
                return ResourceManager.GetString("Tip_1_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courts that hear conviction and sentence appeals together should check this box..
        /// </summary>
        public static string Tip_1_2_Checkbox {
            get {
                return ResourceManager.GetString("Tip_1_2_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A decision given at hearing (also referred to as Bench decision) is a decision that is rendered immediately after the hearing, the same day of the hearing or during the same sitting week. If a decision is given at the hearing but the reasons follow the pronouncement, which means that the reasons are not provided immediately after the hearing, on the same day of the hearing or on the same sitting week of the hearing, this decision should be counted as a reserved judgment..
        /// </summary>
        public static string Tip_2_1_1 {
            get {
                return ResourceManager.GetString("Tip_2_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A decision given after reserving is a decision that is rendered at a later date, i.e., not immediately after the hearing, not on the same day of the hearing and not during the same sitting week..
        /// </summary>
        public static string Tip_2_1_2 {
            get {
                return ResourceManager.GetString("Tip_2_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A decision given at hearing (also referred to as Bench decision) is a decision that is rendered immediately after the hearing, the same day of the hearing or during the same sitting week. If a decision is given at the hearing but the reasons follow the pronouncement, which means that the reasons are not provided immediately after the hearing, on the same day of the hearing or on the same sitting week of the hearing, this decision should be counted as a reserved judgment.&lt;br /&gt;&lt;br /&gt;The decisions involving t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tip_2_2_1 {
            get {
                return ResourceManager.GetString("Tip_2_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples of other criminal appeals are habeas corpus, prohibition, certiorari, mental disorder reviews, etc..
        /// </summary>
        public static string Tip_2_2_1_3 {
            get {
                return ResourceManager.GetString("Tip_2_2_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A decision filed after reserving is a decision that is rendered at a later date i.e. not on the same day of the hearing or during the same sitting week. If a decision is given at the hearing but the reasons follow the pronouncement i.e., they are not provided immediately after the hearing, on the same day of the hearing or during the same sitting week, this decision should be counted as a reserved judgment..
        /// </summary>
        public static string Tip_2_2_2 {
            get {
                return ResourceManager.GetString("Tip_2_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples of criminal appeals are habeas corpus, prohibition, certiorari, mental disorder reviews..
        /// </summary>
        public static string Tip_2_2_2_3 {
            get {
                return ResourceManager.GetString("Tip_2_2_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bench decisions/judgments are also referred to as decisions given at hearing. A Bench decision or decision given at hearing is rendered immediately after the hearing, the same day of the hearing or during the same sitting week. The decisions involving the &lt;i&gt;Youth Criminal Justice Act&lt;/i&gt; are not to be tracked separately. They should be counted as any other decision/judgment..
        /// </summary>
        public static string Tip_3_1 {
            get {
                return ResourceManager.GetString("Tip_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reserved decision is a decision that is rendered at a later date i.e. not immediately after the hearing, not on the same day of the hearing nor during the same sitting week. The decisions involving the &lt;i&gt;Youth Criminal Justice Act&lt;/i&gt; are not to be tracked separately. They should be counted as any other criminal appeal decision..
        /// </summary>
        public static string Tip_3_2 {
            get {
                return ResourceManager.GetString("Tip_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For criminal cases, the time intervals and time periods should be reported for each of the following three categories of criminal appeals: 1) Conviction/acquittal, 2) Sentence, and 3) Other..
        /// </summary>
        public static string Tip_4_1_CriminalCases {
            get {
                return ResourceManager.GetString("Tip_4_1_CriminalCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil and criminal case statistics are to be collected for three time intervals: 1) Notice of appeal to filing of the appellant’s factum (or the equivalent document), 2) Filing of appellant’s factum to hearing, and 3) Hearing to final decision.&lt;br /&gt;&lt;br /&gt;For each of these time intervals, information will be gathered for three time periods: 1) Less than 6 months, 2) Between 6 to 12 months, and 3) More than 12 months..
        /// </summary>
        public static string Tip_4_Heading {
            get {
                return ResourceManager.GetString("Tip_4_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The court for which the submission applies..
        /// </summary>
        public static string Tip_Court {
            get {
                return ResourceManager.GetString("Tip_Court", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For criminal cases, the time intervals and time periods should be reported for each of the following three categories of criminal appeals: 1) Conviction/acquittal, 2) Sentence, and 3) Other..
        /// </summary>
        public static string Tip_CriminalCases {
            get {
                return ResourceManager.GetString("Tip_CriminalCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date of the period covered by the submission..
        /// </summary>
        public static string Tip_FromDate {
            get {
                return ResourceManager.GetString("Tip_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reporting year for the data..
        /// </summary>
        public static string Tip_ReportingYear {
            get {
                return ResourceManager.GetString("Tip_ReportingYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date of the period covered by the submission..
        /// </summary>
        public static string Tip_ToDate {
            get {
                return ResourceManager.GetString("Tip_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date is required.
        /// </summary>
        public static string ToDateRequired {
            get {
                return ResourceManager.GetString("ToDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Incomplete: All fields are mandatory. Please enter 0 to indicate that no data is being submitted..
        /// </summary>
        public static string Validation_FormIncomplete {
            get {
                return ResourceManager.GetString("Validation_FormIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
