<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
	<UserSecretsId>7fe53468-ad76-4d48-9ff2-9e69d717cb60</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\lib\GCWeb-master\**" />
    <Content Remove="wwwroot\lib\GCWeb-master\**" />
    <EmbeddedResource Remove="wwwroot\lib\GCWeb-master\**" />
    <None Remove="wwwroot\lib\GCWeb-master\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Pages\Index1.cshtml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Pages\Index1.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Web" Version="4.3.0" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="4.3.0" />
    <PackageReference Include="Microsoft.PowerBI.Api" Version="5.1.0" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.24" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SmartBreadcrumbs" Version="3.6.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Pages\CreateModel.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CreateModel.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Pages\IndexModel.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IndexModel.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Pages\ReportModel.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ReportModel.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Pages\ReviewModel.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ReviewModel.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Pages\SelectModel.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SelectModel.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\images\background.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\images\bg.jpeg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Pages\CreateModel.en.resx">
      <Generator></Generator>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\CreateModel.fr.resx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\CreateModel.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CreateModel.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\IndexModel.en.resx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\IndexModel.fr.resx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\IndexModel.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>IndexModel.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\ReportModel.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ReportModel.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\ReviewModel.en.resx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\ReviewModel.fr.resx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\ReviewModel.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ReviewModel.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\SelectModel.en.resx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\SelectModel.fr.resx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Pages\SelectModel.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SelectModel.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>
